

# include:
#     - Source            # Inspect all Swift files under "Source/"
exclude:
    - Pods                # Ignore Swift files under "Pods/"
    - Carthage            # Ignore Swift files under "Carthage/"

# Tailor will check for violations to all rules except for the following ones
except:
    - constant-k-prefix
    - function-whitespace
    - leading-whitespace
