#
# NOTE:
# To fix `trailing_whitespace` error,
# go to Xcode Preferences -> Text Editing -> turn on both "Automatically trim trailing whitespace" and "Including whitespace-only lines".
#

disabled_rules:
  - variable_name_min_length
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity

  - opening_brace         # prefer Allman-Style
  - statement_position    # allow `if {}\nelse {}`
  - type_name             # allow "_" prefix name
  - variable_name         # allow "_" prefix name
  - todo
  - valid_docs

opt_in_rules:
  - empty_count

#included:
#  - Sources
#  - Tests

excluded:
  - Carthage
  - Packages
  - Benchmark/Packages

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
